version: '3.8'

services:
  # --- DATABASE POSTGRESQL ---
  postgres:
    image: postgres:15-alpine
    container_name: cosmetics_db_container
    restart: always
    environment:
      POSTGRES_DB: cosmetics_db
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_password_123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- CÔNG CỤ QUẢN LÝ PGADMIN (Tùy chọn, rất khuyên dùng) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: cosmetics_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cosmetics.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

# Khai báo volume để dữ liệu không bị mất khi tắt container
volumes:
  postgres_data: